### ISSUE TITLE
Broken navigation links in news articles

### ISSUE THREAD

**Issue by d2s** [EuropeanTestingConference/europeantestingconference#4]
Noticed that top navigation URLs in [TestLab is Open](http://europeantestingconference.eu/news/TestLab-Is-Open) –page are lacking the working URL.

For example, link to Speakers page is in this format:
```
<a href="//speakers/">Speakers</a>
```

Should point to http://europeantestingconference.eu/2017/speakers/
```
<a href="http://europeantestingconference.eu/2017/speakers/">Speakers</a>
```

Most likely the *URL generation* has gotten confused as part of the site is located
under `2017` while the news section (at least) are at the root of the domain URL.

**Comment by p00j4** [comment]
@franziskas I too have encountered similar issue recently 
from [this page](http://europeantestingconference.eu/news/Call-for-Collaboration-2018), all the links on top menu are not working. Here is the short [video](https://drive.google.com/file/d/0B7KEfVSzj9D4dXNuSU9Vajd1WDA/view)
**Possible reason:** re-route logic in configuration, from this page (/news/) is not getting resolved. 
Note: the same paths, works perfectly from the [/2018/](http://europeantestingconference.eu/2018/) page

**Comment by jukecraft** [comment]
@p00j4 Thank you for your detailed report! We're aware of some of these issues but will take another look. 

We're working on major changes to the pages and this not given fixing the attention it needs. 
@rinkkasatiainen is there something quick you can do?

**Comment by rinkkasatiainen** [comment]
Hi, 
Thanks. I am currently working on a major changes to the site. Hopefully I am able to publish those (at least internally) this week. 

I'll look into these while working on the new layout.

Thanks!

**Comment by rinkkasatiainen** [comment]
Fixed with new layout changes
